### ISSUE TITLE
Add a role observer to etcd

### ISSUE THREAD

**Issue by tuteng** [jingyih/etcd#18]
Is it necessary to promote learner as an observer? Similar to the observer of zookeeper, it does not participate in voting but copies data and synchronizes data to other systems, such as CDC.
Observer is not part of raft protocol, can we add observer to Attributes of [member.go](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/membership/member.go)?

**Comment by jingyih** [comment]
Can you post this issue in `etcd-io/etcd` so that it gets more attention? I guess if etcd is facing reading scalability issues, observer would be a solution. In future, I think learner (who's progress is caught up with the leader) will support linearizable reads, so it can act as read only replica.
